accelerate launch sdxl_train_control_net_lllite.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --network_weights="checkpoints/bdsqlsz_controlllite_xl_mlsd_V2.safetensors" \
  --train_data_dir="dataset/diffuse" \
  --conditioning_data_dir="dataset/uv_inv" \
  --caption_extension=".txt" \
  --resolution="512,512" \
  --train_batch_size=1 \
  --max_train_epochs=80 \
  --gradient_accumulation_steps=16 \
  --mixed_precision="bf16" \
  --save_precision="bf16" \
  --save_every_n_epochs=5 \
  --cond_emb_dim=256 \
  --network_dim=64 \
  --learning_rate=2e-5 \
  --output_dir="trainings" \
  --output_name="sdxl_16bs_-5lr_2k_inv"

#   usage: sdxl_train_control_net_lllite.py [-h] [--console_log_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
#                                         [--console_log_file CONSOLE_LOG_FILE] [--console_log_simple] [--v2]
#                                         [--v_parameterization]
#                                         [--pretrained_model_name_or_path PRETRAINED_MODEL_NAME_OR_PATH]
#                                         [--tokenizer_cache_dir TOKENIZER_CACHE_DIR] [--metadata_title METADATA_TITLE]
#                                         [--metadata_author METADATA_AUTHOR] [--metadata_description METADATA_DESCRIPTION]
#                                         [--metadata_license METADATA_LICENSE] [--metadata_tags METADATA_TAGS]
#                                         [--metadata_usage_hint METADATA_USAGE_HINT] [--metadata_thumbnail METADATA_THUMBNAIL]
#                                         [--metadata_merged_from METADATA_MERGED_FROM]
#                                         [--metadata_trigger_phrase METADATA_TRIGGER_PHRASE]
#                                         [--metadata_preprocessor METADATA_PREPROCESSOR]
#                                         [--metadata_is_negative_embedding METADATA_IS_NEGATIVE_EMBEDDING]
#                                         [--train_data_dir TRAIN_DATA_DIR] [--cache_info] [--shuffle_caption]
#                                         [--caption_separator CAPTION_SEPARATOR] [--caption_extension CAPTION_EXTENSION]
#                                         [--caption_extention CAPTION_EXTENTION] [--keep_tokens KEEP_TOKENS]
#                                         [--keep_tokens_separator KEEP_TOKENS_SEPARATOR]
#                                         [--secondary_separator SECONDARY_SEPARATOR] [--enable_wildcard]
#                                         [--caption_prefix CAPTION_PREFIX] [--caption_suffix CAPTION_SUFFIX] [--color_aug]
#                                         [--flip_aug] [--face_crop_aug_range FACE_CROP_AUG_RANGE] [--random_crop]
#                                         [--debug_dataset] [--resolution RESOLUTION] [--cache_latents]
#                                         [--vae_batch_size VAE_BATCH_SIZE] [--cache_latents_to_disk] [--skip_cache_check]
#                                         [--enable_bucket] [--min_bucket_reso MIN_BUCKET_RESO]
#                                         [--max_bucket_reso MAX_BUCKET_RESO] [--bucket_reso_steps BUCKET_RESO_STEPS]
#                                         [--bucket_no_upscale]
#                                         [--resize_interpolation {lanczos,nearest,bilinear,linear,bicubic,cubic,area}]
#                                         [--token_warmup_min TOKEN_WARMUP_MIN] [--token_warmup_step TOKEN_WARMUP_STEP]
#                                         [--alpha_mask] [--dataset_class DATASET_CLASS]
#                                         [--caption_dropout_rate CAPTION_DROPOUT_RATE]
#                                         [--caption_dropout_every_n_epochs CAPTION_DROPOUT_EVERY_N_EPOCHS]
#                                         [--caption_tag_dropout_rate CAPTION_TAG_DROPOUT_RATE] [--in_json IN_JSON]
#                                         [--dataset_repeats DATASET_REPEATS] [--output_dir OUTPUT_DIR]
#                                         [--output_name OUTPUT_NAME] [--huggingface_repo_id HUGGINGFACE_REPO_ID]
#                                         [--huggingface_repo_type HUGGINGFACE_REPO_TYPE]
#                                         [--huggingface_path_in_repo HUGGINGFACE_PATH_IN_REPO]
#                                         [--huggingface_token HUGGINGFACE_TOKEN]
#                                         [--huggingface_repo_visibility HUGGINGFACE_REPO_VISIBILITY]
#                                         [--save_state_to_huggingface] [--resume_from_huggingface] [--async_upload]
#                                         [--save_precision {None,float,fp16,bf16}] [--save_every_n_epochs SAVE_EVERY_N_EPOCHS]
#                                         [--save_every_n_steps SAVE_EVERY_N_STEPS] [--save_n_epoch_ratio SAVE_N_EPOCH_RATIO]
#                                         [--save_last_n_epochs SAVE_LAST_N_EPOCHS]
#                                         [--save_last_n_epochs_state SAVE_LAST_N_EPOCHS_STATE]
#                                         [--save_last_n_steps SAVE_LAST_N_STEPS]
#                                         [--save_last_n_steps_state SAVE_LAST_N_STEPS_STATE] [--save_state]
#                                         [--save_state_on_train_end] [--resume RESUME] [--train_batch_size TRAIN_BATCH_SIZE]
#                                         [--max_token_length {None,150,225}] [--mem_eff_attn] [--torch_compile]
#                                         [--dynamo_backend {eager,aot_eager,inductor,aot_ts_nvfuser,nvprims_nvfuser,cudagraphs,ofi,fx2trt,onnxrt,tensort,ipex,tvm}]
#                                         [--xformers] [--sdpa] [--vae VAE] [--max_train_steps MAX_TRAIN_STEPS]
#                                         [--max_train_epochs MAX_TRAIN_EPOCHS]
#                                         [--max_data_loader_n_workers MAX_DATA_LOADER_N_WORKERS]
#                                         [--persistent_data_loader_workers] [--seed SEED] [--gradient_checkpointing]
#                                         [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
#                                         [--mixed_precision {no,fp16,bf16}] [--full_fp16] [--full_bf16] [--fp8_base]
#                                         [--ddp_timeout DDP_TIMEOUT] [--ddp_gradient_as_bucket_view] [--ddp_static_graph]
#                                         [--clip_skip CLIP_SKIP] [--logging_dir LOGGING_DIR]
#                                         [--log_with {tensorboard,wandb,all}] [--log_prefix LOG_PREFIX]
#                                         [--log_tracker_name LOG_TRACKER_NAME] [--wandb_run_name WANDB_RUN_NAME]
#                                         [--log_tracker_config LOG_TRACKER_CONFIG] [--wandb_api_key WANDB_API_KEY]
#                                         [--log_config] [--noise_offset NOISE_OFFSET] [--noise_offset_random_strength]
#                                         [--multires_noise_iterations MULTIRES_NOISE_ITERATIONS]
#                                         [--ip_noise_gamma IP_NOISE_GAMMA] [--ip_noise_gamma_random_strength]
#                                         [--multires_noise_discount MULTIRES_NOISE_DISCOUNT]
#                                         [--adaptive_noise_scale ADAPTIVE_NOISE_SCALE] [--zero_terminal_snr]
#                                         [--min_timestep MIN_TIMESTEP] [--max_timestep MAX_TIMESTEP]
#                                         [--loss_type {l1,l2,huber,smooth_l1}] [--huber_schedule {constant,exponential,snr}]
#                                         [--huber_c HUBER_C] [--huber_scale HUBER_SCALE] [--lowram] [--highvram]
#                                         [--sample_every_n_steps SAMPLE_EVERY_N_STEPS] [--sample_at_first]
#                                         [--sample_every_n_epochs SAMPLE_EVERY_N_EPOCHS] [--sample_prompts SAMPLE_PROMPTS]
#                                         [--sample_sampler {ddim,pndm,lms,euler,euler_a,heun,dpm_2,dpm_2_a,dpmsolver,dpmsolver++,dpmsingle,k_lms,k_euler,k_euler_a,k_dpm_2,k_dpm_2_a}]
#                                         [--config_file CONFIG_FILE] [--output_config] [--deepspeed] [--zero_stage {0,1,2,3}]
#                                         [--offload_optimizer_device {None,cpu,nvme}]
#                                         [--offload_optimizer_nvme_path OFFLOAD_OPTIMIZER_NVME_PATH]
#                                         [--offload_param_device {None,cpu,nvme}]
#                                         [--offload_param_nvme_path OFFLOAD_PARAM_NVME_PATH] [--zero3_init_flag]
#                                         [--zero3_save_16bit_model] [--fp16_master_weights_and_gradients]
#                                         [--optimizer_type OPTIMIZER_TYPE] [--use_8bit_adam] [--use_lion_optimizer]
#                                         [--learning_rate LEARNING_RATE] [--max_grad_norm MAX_GRAD_NORM]
#                                         [--optimizer_args [OPTIMIZER_ARGS ...]] [--lr_scheduler_type LR_SCHEDULER_TYPE]
#                                         [--lr_scheduler_args [LR_SCHEDULER_ARGS ...]] [--lr_scheduler LR_SCHEDULER]
#                                         [--lr_warmup_steps LR_WARMUP_STEPS] [--lr_decay_steps LR_DECAY_STEPS]
#                                         [--lr_scheduler_num_cycles LR_SCHEDULER_NUM_CYCLES]
#                                         [--lr_scheduler_power LR_SCHEDULER_POWER] [--fused_backward_pass]
#                                         [--lr_scheduler_timescale LR_SCHEDULER_TIMESCALE]
#                                         [--lr_scheduler_min_lr_ratio LR_SCHEDULER_MIN_LR_RATIO]
#                                         [--dataset_config DATASET_CONFIG] [--min_snr_gamma MIN_SNR_GAMMA]
#                                         [--scale_v_pred_loss_like_noise_pred] [--v_pred_like_loss V_PRED_LIKE_LOSS]
#                                         [--debiased_estimation_loss] [--weighted_captions] [--cache_text_encoder_outputs]
#                                         [--cache_text_encoder_outputs_to_disk] [--disable_mmap_load_safetensors]
#                                         [--save_model_as {None,ckpt,pt,safetensors}] [--cond_emb_dim COND_EMB_DIM]
#                                         [--network_weights NETWORK_WEIGHTS] [--network_dim NETWORK_DIM]
#                                         [--network_dropout NETWORK_DROPOUT] [--conditioning_data_dir CONDITIONING_DATA_DIR]
#                                         [--no_half_vae]